### ISSUE TITLE
Agents are not rendered

### ISSUE THREAD

**Issue by ARDev1161** [robotics-upo/hunav_gazebo_wrapper#11]
Hello @noeperez  , @roberottt 

I run the example - ros2 launch hunav_gazebo_wrapper example_cafe.launch.py ​​but only actor3 (robot) is rendered and agents are not(but in rviz2 I can see their movements). Tell me what I'm doing wrong. Thanks in advance

![image](https://github.com/user-attachments/assets/31dcc392-dceb-4879-8c82-24395f317d0b)

**Comment by noeperez** [comment]
Hi, 

sorry but Ignacio-Perez is not a contributor of this repository.

Secondly, I have created a new workspace and I have downloaded the code (hunav_sim and hunav_gazebo_wrapper) and I can run the example cafe without any problem. Are you using ROS2 Humble and Gazebo 11? or are you using the provided docker?

**Comment by ARDev1161** [comment]
Hello sorry for the mistake with tags. Yes I use humble with Gazebo 11

**Comment by noeperez** [comment]
It is really weird. We have never had that problem. 
HuNavSim is working since you can see the agent TFs on RViz. So I guess it is something related to Gazebo and the animated human models, but I have no clue about what can be missing. ...did you source the /usr/share/gazebo/setup.sh as indicated in the dependencies section?

**Comment by ARDev1161** [comment]
So, I tried to make a new WS with only hunav_sim hunav_gazebo_wrapper & people, and I had the same issue. Can it be related to NVidia drivers?

**Comment by ARDev1161** [comment]
Maybe thyis log can say something about my problem? I didn't see any problem, but maybe I miss [log.txt](https://github.com/user-attachments/files/17256672/log.txt)

**Comment by ARDev1161** [comment]
> /usr/share/gazebo/setup.sh

Yes I tried to source this file, but it doesn't help. I also add it to my .zshrc

**Comment by noeperez** [comment]
I do not see any error in the log. All the HuNavSim nodes are ok, so it is something related to Gazebo definitely. 
I would say that Gazebo is using your GPU properly because of the colors that I see in the capture you sent, but it is something that you can check. When you run Gazebo, execute "nvidia-smi" in the terminal to see the processes that are using your gpu.  
To be honest, I do not have any idea about possible solutions at the moment. We have the simulator running in different computers without that problem.

**Comment by ARDev1161** [comment]
Well, I got it but I don't see any problems.. I'll try to setup new clear Ubuntu
![image](https://github.com/user-attachments/assets/380d4a33-ec27-40a0-a85c-99a1d8257544)

**Comment by ARDev1161** [comment]
There is something really wrong with the gazebo. On another machine the simulation worked fine.
