### ISSUE TITLE
Cannot launch the whole pipeline because of broken deps

### ISSUE THREAD

**Issue by Steplerchik** [robotics-upo/hunav_gazebo_wrapper#5]
Hello! Please, could you provide some dockerfile and corresponding to it files so I can build an image and run the pipeline with evaluating metrics for some robot? All my tries failed, so currently it seems impossible to run neither under foxy nor under humble. Thank you in advance!

**Comment by noeperez** [comment]
Hello!
The Humble version is still under development. The Foxy one should be the more stable. Please use that one. 
Are you able to launch the given examples? The example with an actor playing the robot role is working (example_cafe.launch.py)? Could you copy the errors that you get? Which deps are missing?
To provide a complete example including a robot is not easy. The system is devised to include the human pedestrians in whatever robot simulation the user is using. Anyway, you have an example launch of the system with a robot (pmb2_cafe.launch.py). It includes the pmb2 robot but the required files to simulate the robot are not included since they are provided by a third company (PAL Robotics).   
The idea of providing a dockerfile is interesting. We will consider it. Unfortunately, we are really busy these days and I will not be ready very soon.

**Comment by Steplerchik** [comment]
Dear @noeperez,

Thank you for your response!
First, I tried the stable foxy version, ofc. The scene with the actor playing the robot's role was fine. However, when again I tried the scene with the PAL Robotics robot, an error raised, which required the libgazebo_world_odometry.so library, BUT the corresponding package [does not provide](https://github.com/pal-robotics/pal_gazebo_plugins/blob/foxy-devel/CMakeLists.txt) this lib. So, the questions are following:
1) How did you install this library (libgazebo_world_odometry.so) for foxy?;
2) What launch examples did work for you?;
3) Please could you provide a list of deps so I can install them by rosdep install command? Maybe there is smth wrong with package releases (commits) you and I are using.

Well, then I moved to humble and tried to run the example (pmb2_cafe.launch.py). I followed your [tips](https://github.com/robotics-upo/hunav_gazebo_wrapper/tree/humble#tips) provided in README.md. However, humans are not moving after I run the simulation. Also, the robot's wheels are placed at zero coords. I thought the problem was with the PAL Robotics packages, but I ran their pure [simulation](https://github.com/pal-robotics/pmb2_simulation/tree/humble-devel#simulation), and it was totally fine.

![Example of running pmb2_cafe.launch.py, wheels are at the origin](https://github.com/robotics-upo/hunav_gazebo_wrapper/assets/43290347/6616600b-5da8-40e6-89ac-ca6b6810a45c)

P.S. If I succeed in running your simulation, I can open a pull request and provide you a Dockerfile with corresponding build scripts to make everything installed by one command.

**Comment by noeperez** [comment]
Hello!
sorry, I did not explain myself properly.
HuNavSim (and its dependencies) is working properly since you can run example_cafe.launch.py.
We do not have available here a complete simulation of the HuNav agents with a robot. It is up to the user to integrate the HuNav agents in the robot simulation that she wants. 
The pmb2_cafe.launch.py is just an example of how to include the spawning of a robot in the launch file along with HuNavSim, but it is NOT working since we do not provide the simulation files of the pmb2 robot.
You should have a robot simulation in Gazebo (we tested with Gazebo 11), and then, you can create a new launch file that integrates the human agents in your robot simulation.   

To ease the set up, we will provide a dockerfile that integrates an example robot simulation along with HuNavSim. But, as I said before, It will not be ready soon since we do not have time to do it for the moment.

**Comment by Steplerchik** [comment]
Thank you for clarification! I look forward to it.

**Comment by sskorol** [comment]
@Steplerchik you can check changes I made to support [humble](https://github.com/robotics-upo/hunav_gazebo_wrapper/issues/1#issuecomment-1383254569). These branches are a bit outdated. But at least you'll get an idea what's required to be changed. But I was able to run simulation with this snapshot.

**Comment by nanaminh** [comment]
Hello, did anyone manage to run "pmb2_cafe.launch.py" with the robot in the foxy version? If so, could you share the steps you have taken? I am struggling on that right now. 
Thank you in advance.

**Comment by noeperez** [comment]
Hi, the pmb2_cafe.launch.py is just a non-functional example of how to launch the system with a robot. I mean, you need to install all the PAL robotics packages required to simulate the pmb2 robot, and maybe, to modify the provided launch example to run it properly. It is up to the user to use the desired robot. 
HuNavSim is devised to include moving human agents in a robot simulation previously defined by the user.
